#!/usr/bin/env bash

set -e

SLEEP_TIME=10

do_check_and_log() {
    R=`adb_check_if_booted`
    # D=`date`
    D=`date +'%Y-%m-%d %T%H %Z'`
    echo "${D}: ${R}"
}


D=`date +'%Y-%m-%d %T%H %Z'`
echo "${D}: starting"

do_check_and_log
while sleep $SLEEP_TIME; do
    do_check_and_log
done
